apiVersion: v1
kind: ConfigMap
metadata:
  name: analyzegit-config
  namespace: analyzegit
data:
  PORT_GATEWAY: "5000"
  PORT_AUTH: "5001"
  PORT_RECRUITMENT: "5003"
  PORT_ANALYSIS: "5004"
  AUTH_SERVICE_URL: "http://auth-service:5001"
  RECRUITMENT_SERVICE_URL: "http://recruitment-service:5003"
  ANALYSIS_SERVICE_URL: "http://analysis-service:5004"
  MONGO_URI: "mongodb://mongodb:27017/analyzegit"
  REDIS_URL: "redis://redis:6379"
  FRONTEND_URL: "http://localhost:5173"
  AWS_REGION: "ap-south-1"
  AWS_S3_BUCKET_NAME: "analyzegit-resumes-bucket"
---
apiVersion: v1
kind: Secret
metadata:
  name: analyzegit-secrets
  namespace: analyzegit
type: Opaque
stringData:
  JWT_SECRET: "your-jwt-secret-key-here"
  GEMINI_API_KEY: "your-gemini-api-key-here"
  GITHUB_TOKEN: "your-github-personal-access-token-here"
  BREVO_API_KEY: "your-brevo-api-key-here"
  BREVO_SENDER_EMAIL: "your-brevo-sender-email-here"
  AWS_ACCESS_KEY_ID: "your-aws-access-key-id-here"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-access-key-here"

